# Generated by Django 5.2.8 on 2025-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charactter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.TextField()),
                ('skin_color', models.TextField()),
                ('eye_color', models.TextField()),
                ('birth_year', models.IntegerField()),
                ('gender', models.TextField()),
                ('homeworld', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model', models.TextField()),
                ('manufacturer', models.TextField()),
                ('cost_in_credits', models.IntegerField()),
                ('length', models.IntegerField()),
                ('max_atmosphering_speed', models.IntegerField()),
                ('crew', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('cargo_capacity', models.IntegerField()),
                ('consumablesv', models.TextField()),
                ('hyperdrive_rating', models.IntegerField()),
                ('MGLT', models.IntegerField()),
                ('starship_class', models.TextField()),
                ('pilots', models.ManyToManyField(related_name='starships', to='people.charactter')),
            ],
        ),
    ]