# Generated by Django 5.2.8 on 2025-12-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactter',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='starship',
            options={'verbose_name': 'Корабль', 'verbose_name_plural': 'Корабли'},
        ),
    ]